%%
% |%%%% MAIN MENU| 
close all;

%creating the main menu
Fig=figure('Name','CAG Project ~ Negrea Sara',...
    'Units','normalized',...
    'Position',[0.1 0.1 0.8 0.7],...
    'color','none',...
    'NumberTitle','off');
backgroundimg =imread('milkyway.jpg');   %imread() allows us to 'read' the image

backgroundAxes = axes('Parent', Fig, 'Position', [0, 0, 1, 1]);
%%
imagesc(backgroundimg);    %this one sets the previous image as a backround
set(backgroundAxes, 'handlevisibility', 'off', 'visible', 'off');

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.3 0.85 0.35 0.1],...
    'backgroundcolor','#FFFFFF',...',...
    'foregroundcolor',"#330066",...
    'Fontname','Times New Roman',...
    'FontWeight','Bold',...
    'FontSize',30,...
    'String','The Solar System');

uicontrol('Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.45 0.75 0.2 0.05], ...
    'BackgroundColor', '#FFFFFF', ...
    'ForegroundColor', "#330066", ...
    'FontName', 'Times New Roman', ...
    'FontWeight', 'Bold', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'center', ...
    'String', 'by Negrea Sara Diana');


%%
% _%%mercury_ 
uicontrol('style','pushbutton',...
    'Units','normalized',...
    'Position',[0.05 0.8 0.16 0.06],...
    'string','I. MERCURY',...
    'FontName','Times New Roman',...
    'FontSize',12,...
    'backgroundcolor',[0.42, 0.35, 0.63],...',...
    'foregroundcolor',"#FFFFFF",...
    'Callback','mercury_interface');

%%
% _%venus_ 
uicontrol('style','pushbutton',...
    'Units','normalized',...
    'Position',[0.05 0.7 0.16 0.06],...
    'string','II. VENUS',...
    'FontName','Times New Roman',...
    'FontSize',12,...
    'backgroundcolor',[0.42, 0.35, 0.63],...',...
    'foregroundcolor',"#FFFFFF",...
    'Callback','venus_interface');

%%
% _%%earth_ 
uicontrol('style','pushbutton',...
    'Units','normalized',...
    'Position',[0.05 0.6 0.16 0.06],...
    'string','III. EARTH',...
    'FontName','Times New Roman',...
    'FontSize',12,...
    'backgroundcolor',[0.42, 0.35, 0.63],...',...
    'foregroundcolor',"#FFFFFF",...
    'Callback','earth_interface');

%%
% _%%mars_ 
uicontrol('style','pushbutton',...
    'Units','normalized',...
    'Position',[0.05 0.5 0.16 0.06],...
    'string','IV. MARS',...
    'FontName','Times New Roman',...
    'FontSize',12,...
    'backgroundcolor',[0.42, 0.35, 0.63],...',...
    'foregroundcolor',"#FFFFFF",...
    'Callback','mars_interface');

%%
% _%%jupiter_ 
uicontrol('style','pushbutton',...
    'Units','normalized',...
    'Position',[0.05 0.4 0.16 0.06],...
    'string','V. JUPITER',...
    'FontName','Times New Roman',...
    'FontSize',12,...
    'backgroundcolor',[0.42, 0.35, 0.63],...',...
    'foregroundcolor',"#FFFFFF",...
    'Callback','jupiter_interface');

%%
% _%saturn_ 
uicontrol('style','pushbutton',...
    'Units','normalized',...
    'Position',[0.05 0.3 0.16 0.06],...
    'string','VI. SATURN',...
    'FontName','Times New Roman',...
    'FontSize',12,...
    'backgroundcolor',[0.42, 0.35, 0.63],...',...
    'foregroundcolor',"#FFFFFF",...
    'Callback','saturn_interface');
%%
% _
%uranus_ 
uicontrol('style','pushbutton',...
    'Units','normalized',...
    'Position',[0.05 0.2 0.16 0.06],...
    'string','VII. URANUS',...
    'FontName','Times New Roman',...
    'FontSize',12,...
    'backgroundcolor',[0.42, 0.35, 0.63],...',...
    'foregroundcolor',"#FFFFFF",...
    'Callback','uranus_interface');

%%
% _%%neptune_ 
uicontrol('style','pushbutton',...
    'Units','normalized',...
    'Position',[0.05 0.1 0.16 0.06],...
    'string','VIII. NEPTUNE',...
    'FontName','Times New Roman',...
    'FontSize',12,...
    'backgroundcolor',[0.42, 0.35, 0.63],...',...
    'foregroundcolor',"#FFFFFF",...
    'Callback','neptune_interface');


%%
% _%display_solar_system_button_ 
uicontrol('style','pushbutton',...
    'Units','normalized',...
    'Position',[0.35 0.45 0.3 0.12],...
    'string','DISPLAY SOLAR SYSTEM',...
    'FontName','Times New Roman',...
    'FontSize',14,...
    'backgroundcolor',[0.9, 0.6, 0.6],...',...
    'foregroundcolor',"#FFFFFF",...
    'Callback','solarsyst');

%%documentation
uicontrol('style','pushbutton',...
    'Units','normalized',...
    'Position',[0.85 0.15 0.10 0.06],...
    'string','~documentation~',...
    'FontName','Times New Roman',...
    'FontSize',12,...
    'backgroundcolor',[0, 0.0, 0.3],...',...
    'foregroundcolor',"#FFFFFF",...
    'Callback','open (''the_solar_system.docx'')');
