function radius_neptune()

    planets = {'MERCURY', 'VENUS', 'EARTH', 'MARS', 'JUPITER', 'SATURN', 'URANUS', 'NEPTUNE'};
    radii = [2439, 6051.8, 6371, 3389, 69911, 58232, 25362, 24622]; % Radii in km

    uicontrol('Style', 'text', ...
              'Units', 'normalized', ...
              'Position', [0.65, 0.85, 0.35, 0.05], ...
              'String', 'Select a planet to see its radius and surface area:', ...
              'ForegroundColor', 'white', ...
              'BackgroundColor', [0 0.2 0.4], ...
              'FontSize', 14, ...
              'FontName', 'Times New Roman', ...
              'HorizontalAlignment', 'center');

    popup = uicontrol('Style', 'popupmenu', ...
                      'Units', 'normalized', ...
                      'Position', [0.75, 0.74, 0.15, 0.08], ...
                      'String', planets, ...
                      'FontName', 'Times New Roman', ...
                      'FontSize', 12, ...
                      'HorizontalAlignment', 'center',...
                      'BackgroundColor', [0.4 0.6 0.7], ...
                      'ForegroundColor', 'white', ...
                      'Callback', @update_radius);

    % Text to display the selected planet's radius
radiusText = uicontrol('Style', 'text', ...
                           'Units', 'normalized', ...
                           'Position', [0.7, 0.68, 0.25, 0.05], ...
                           'ForegroundColor', 'white', ...
                           'BackgroundColor', [0 0.2 0.4], ...
                           'FontName', 'Times New Roman', ...
                           'FontSize', 14, ...
                           'HorizontalAlignment', 'center');

    %button for area
calcButton = uicontrol('Style', 'pushbutton', ...
                           'Units', 'normalized', ...
                           'Position', [0.75, 0.6, 0.2, 0.05], ...
                           'FontSize', 12, ...
                           'ForegroundColor', 'white', ...
                           'BackgroundColor', [0.4 0.3 0.9], ...
                           'String', 'CALCULATE SURFACE AREA', ...
                           'Callback', @calculate_surface_area);

%calculated area
    resultText = uicontrol('Style', 'text', ...
                           'Units', 'normalized', ...
                           'Position', [0.7, 0.45, 0.3, 0.05], ...
                           'BackgroundColor', [0 0.2 0.4], ...
                           'ForegroundColor', 'white', ...
                           'FontName', 'Times New Roman', ...
                           'FontWeight', 'Bold', ...
                           'FontSize', 15, ...
                           'String', '');

    %closebutton
 uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.85 0.05 0.10 0.06],...
          'string','CLOSE',...
          'FontName','Times New Roman',...
          'FontSize',12,...
           'backgroundcolor',[0.1 0.1 0.2],...',...
        'foregroundcolor','white',...
          'Callback','interface');


    function update_radius(~, ~)
        selectedIndex = popup.Value;
        selectedRadius = radii(selectedIndex);
        radiusText.String = sprintf('Radius of %s: %.1f km', ...
                                    planets{selectedIndex}, selectedRadius);
    end

    function calculate_surface_area(~, ~)
        % Get the selected planet index
        selectedIndex = popup.Value;
        
        % Get the radius of the selected planet
        radius = radii(selectedIndex);
        
        % Calculate surface area
        surfaceArea = 4 * pi * radius^2;
        
        % Update the result text
        resultText.String = sprintf('%s is %.2f km^2', ...
                                    planets{selectedIndex}, surfaceArea);
    end
end