function surface_mercury()
    % Radii of planets in kilometers
    planets = {'Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'};
    radii = [2440, 6051.8, 6371, 3389.5, 69911, 58232, 25362, 24622]; % Radii in km
    
    % Close all existing figures
    close all;
  

    % Add popup menu for planet selection
    popup = uicontrol('Style', 'popupmenu', ...
                      'Units', 'normalized', ...
                      'Position', [0.35 0.7 0.3 0.05], ...
                      'String', planets, ...
                      'FontSize', 12);
    
    % Add button to calculate surface area
    calcButton = uicontrol('Style', 'pushbutton', ...
                           'Units', 'normalized', ...
                           'Position', [0.4 0.6 0.2 0.08], ...
                           'FontSize', 12, ...
                           'String', 'Calculate Surface Area', ...
                           'Callback', @calculate_surface_area);

    % Add a text box to display the result
    resultText = uicontrol('Style', 'text', ... 
                           'Units', 'normalized', ...
                           'Position', [0.2 0.4 0.6 0.1], ...
                           'BackgroundColor', [0 0.0 0.2], ...
                           'ForegroundColor', 'white', ...
                           'FontName', 'Times New Roman', ...
                           'FontWeight', 'Bold', ...
                           'FontSize', 16, ...
                           'String', '');

    % Callback function to calculate surface area
    function calculate_surface_area(~, ~)
        % Get the selected planet index
        selectedIndex = popup.Value;
        
        % Get the radius of the selected planet
        radius = radii(selectedIndex);
        
        % Calculate surface area
        surfaceArea = 4 * pi * radius^2; % in km²
        
        % Update the result text
        resultText.String = sprintf('The surface area of %s is %.2f km²', ...
                                     planets{selectedIndex}, surfaceArea);
    end
end
